FROM node:lts-alpine


# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./


# install project dependencies
RUN npm install --no-optional

COPY . .

EXPOSE 8080

CMD [ "npm", "run", "dev" ]


# COPY ./docker/dev-entrypoint.sh ./


# ENTRYPOINT ["/bin/sh", "dev-entrypoint.sh"]
